# Generated by Django 5.1.1 on 2026-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=0, upload_to='avatars', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
