# Generated by Django 5.1.1 on 2026-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения публикации')),
                ('image', models.ImageField(blank=True, upload_to='posts_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'Публикации',
                'default_related_name': 'posts',
            },
        ),
    ]
